/**
 * Fetches per-game Pokédex lists from PokéAPI and writes src/data/gamePokedex.ts
 * Run with: node scripts/fetchGamePokedexes.mjs
 */
import { writeFileSync } from 'fs';

async function fetchWithRetry(url, retries = 3) {
  for (let i = 0; i < retries; i++) {
    try {
      const r = await fetch(url);
      if (!r.ok) throw new Error(`HTTP ${r.status}`);
      return await r.json();
    } catch (e) {
      if (i === retries - 1) throw e;
      await new Promise(res => setTimeout(res, 800 * (i + 1)));
    }
  }
}

async function getIds(pokedexIds) {
  const all = new Set();
  for (const pdexId of pokedexIds) {
    const data = await fetchWithRetry(`https://pokeapi.co/api/v2/pokedex/${pdexId}`);
    for (const entry of data.pokemon_entries) {
      const id = parseInt(entry.pokemon_species.url.split('/').filter(Boolean).pop());
      if (!isNaN(id) && id >= 1 && id <= 1025) all.add(id);
    }
  }
  return [...all].sort((a, b) => a - b);
}

// Map game ID → PokéAPI pokedex IDs to combine
// Reference from listPokedexes.mjs output:
//  2=kanto(151), 3=original-johto(251), 4=hoenn(202), 5=original-sinnoh(151)
//  6=extended-sinnoh(210), 7=updated-johto(256), 8=original-unova(156)
//  9=updated-unova(301), 12=kalos-central(150), 13=kalos-coastal(153)
//  14=kalos-mountain(151), 15=updated-hoenn(211), 16=original-alola(302)
//  21=updated-alola(403), 26=letsgo-kanto(153), 27=galar(400)
//  28=isle-of-armor(211), 29=crown-tundra(210), 30=hisui(242)
//  31=paldea(400), 32=kitakami(200), 33=blueberry(243), 34=lumiose-city(232)
const GAME_POKEDEX_MAP = {
  'rby':  [2],              // Kanto (151)
  'frlg': [2],              // Kanto – same regional dex, Gen 3 mechanics
  'gsc':  [3],              // original-johto includes all 251 (kanto+johto)
  'hgss': [7],              // updated-johto (256)
  'rse':  [4],              // Hoenn (202)
  'oras': [15],             // updated-hoenn (211)
  'dpp':  [6],              // extended-sinnoh / Platinum (210)
  'bdsp': [5],              // original-sinnoh (151 Sinnoh dex)
  'pla':  [30],             // hisui (242)
  'bw':   [8],              // original-unova (156)
  'b2w2': [9],              // updated-unova (301)
  'xy':   [12, 13, 14],     // all three Kalos sub-dexes combined
  'sm':   [16],             // original-alola (302)
  'usum': [21],             // updated-alola (403)
  'lgpe': [26],             // letsgo-kanto (153 — includes Meltan + Melmetal)
  'swsh':     [27],           // galar base game (400)
  'swsh_dlc': [27, 28, 29],  // galar + Isle of Armor + Crown Tundra
  'sv':       [31],           // paldea base game (400)
  'sv_dlc':   [31, 32, 33],  // paldea + Kitakami (Teal Mask) + Blueberry (Indigo Disk)
  'lza':      [34],           // lumiose-city (232)
};

async function main() {
  const result = {};

  for (const [gameId, pdexIds] of Object.entries(GAME_POKEDEX_MAP)) {
    process.stdout.write(`Fetching ${gameId} (pokedex ${pdexIds.join('+')})...`);
    const ids = await getIds(pdexIds);
    result[gameId] = ids;
    console.log(` ${ids.length} Pokémon`);
  }

  const lines = [
    `// Auto-generated by scripts/fetchGamePokedexes.mjs`,
    `// Maps game ID → available national dex IDs`,
    ``,
    `const raw: Record<string, number[]> = {`,
  ];

  for (const [gameId, ids] of Object.entries(result)) {
    lines.push(`  '${gameId}': [${ids.join(',')}],`);
  }

  lines.push(
    `};`,
    ``,
    `export const GAME_POKEMON_IDS = raw;`,
    ``,
    `// Pre-built Sets for O(1) lookup`,
    `export const GAME_POKEMON_ID_SETS: Record<string, Set<number>> =`,
    `  Object.fromEntries(Object.entries(raw).map(([k, v]) => [k, new Set(v)]));`,
  );

  const outPath = new URL('../src/data/gamePokedex.ts', import.meta.url).pathname;
  writeFileSync(outPath, lines.join('\n') + '\n');
  console.log(`\nWrote gamePokedex.ts`);
}

main().catch(e => { console.error(e); process.exit(1); });
